version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: football_ai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongpassword

  redis:
    image: redis:7
